name: Docker Image CI

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username riley-momo --password ${{ secrets.GHCR_PAT }} ghcr.io
          docker buildx build -f .devcontainer/Dockerfile -t ghcr.io/riley-momo/souffle-ghcr:latest .
          docker push ghcr.io/riley-momo/souffle-ghcr:latest
